name: Release -> GHCR -> ECS (native Blue/Green)

on:
  release:
    types: [published]

permissions:
  contents: write
  packages: write
  id-token: write   # OIDC vers AWS

env:
  AWS_REGION: eu-west-3

  # ECS
  ECS_CLUSTER: default
  ECS_SERVICE: podinfo
  TASKDEF_FAMILY: podinfo          # family ou ARN de task definition (sans :revision => latest active)
  CONTAINER_NAME: app              # nom du container dans la task definition

  # GHCR
  REGISTRY: ghcr.io
  IMAGE_NAME: ghcr.io/${{ github.repository }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: main
          fetch-depth: 0
        
      - name: Bump version.txt (patch)
        id: bump
        run: |
          VERSION=$(cat version.txt)
          echo "Current version: $VERSION"

          # Supprime le "v", split sur les points
          VERSION_NO_V=${VERSION#v}
          IFS='.' read -r MAJOR MINOR PATCH <<< "$VERSION_NO_V"

          # Incrément patch
          PATCH=$((PATCH + 1))
          NEW_VERSION="v${MAJOR}.${MINOR}.${PATCH}"

          echo "New version: $NEW_VERSION"

          # Écrit dans version.txt
          echo "$NEW_VERSION" > version.txt

          # Expose la version pour les steps suivants
          echo "version=$NEW_VERSION" >> $GITHUB_OUTPUT

      - name: Commit updated version.txt
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

          git add version.txt
          git commit -m "chore: bump version to ${{ steps.bump.outputs.version }}"
          git push origin HEAD:main

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build & push image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: |
            ${{ env.IMAGE_NAME }}:${{ github.ref_name }}
            ${{ env.IMAGE_NAME }}:${{ github.sha }}
